// ////////////////////////////////////////////////////
// Author: Sunil Nanda
// ////////////////////////////////////////////////////

var jsonRecordSchema = {
  created : 0,
  content: {
    L1: "--",
    L2: "--",
    L3: "--",
    L4: "--",
    INITIAL: "--",
    STANDBY: "--",
    RUNNING: "--",
    ERROR: "--",
    MANDATORY: "--",
    SPONTANEOUS: "--",
    BTOG: "--",
    LOST: 0,
    ATTENTION: "--",
    PENDING: "--",
    MODE: "--",
    VT: "--",
    RR: "--",
    EI: "--",
    IPEEP: "--",
    PMAX: "--",
    PS: "--",
    TPS: "--",
    FIO2: "--",
    O2PURIY: "--",
    O2FLOWX10: "--",
    MBPM: "--",
    SBPM: "--",
    STATIC: "--",
    DYNAMIC: "--",
    VTDEL: "--",
    MVDEL: "--",
    PIP: "--",
    PLAT: "--",
    MPEEP: "--",
    TEMP: "--",
    ALT: "--",
    PNAME: "--",
    PMISC: "--",
    PID: "--",
    WMSG: "--",
    EMSG: "--"
  }
};
